version: "3.9"

services:
    postgres:
        image: postgres:16
        container_name: AutService2021547
        restart: always
        environment:
          POSTGRES_DB: bebesito2021547
          POSTGRES_USER: root
          POSTGRES_PASSWORD: admin
        ports:
        - "5437:5432"
        volumes:
        - postgres_data:/var/lib/postgressql/data

volumes:
  postgres_data: